const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function app(){const c={console,setTimeout:()=>{},URLSearchParams,Date,Intl};vm.createContext(c);vm.runInContext(fs.readFileSync('static/script.js','utf8'),c);const a=c.inventoryApp();a.currentUser={id:3,role:'engineer'};return a;}
const result={scope:'own',totals:{events:205,quantity:300,parts:2},rows:[{movement_id:1,quantity:3}],by_part:[],by_work_order:[],limit:100,offset:0};
test('report queries include exact selected filters and reset to first page',async()=>{const a=app();a.reportForm={allDates:false,start_date:'2026-10-01',end_date:'2026-10-05',part_id:'7',store_id:'8',engineer_id:'',work_order_number:' WO-10 '};a.reportOffset=100;a.apiCall=async(p)=>{assert.match(p,/work_order_number=WO-10/);assert.match(p,/part_id=7/);assert.match(p,/offset=0/);return result;};await a.loadConsumptionReport();assert.equal(a.consumptionReport.totals.quantity,300);assert.equal(a.reportOffset,0);});
test('work-order drilldown applies the same filters and performs only GET',async()=>{const a=app();a.reportForm.allDates=true;a.apiCall=async(p,o)=>{assert.equal(o,undefined);assert.match(p,/work_order_number=WO-20/);assert.doesNotMatch(p,/start_date/);return result;};await a.openWorkOrderReport('WO-20');assert.equal(a.reportForm.work_order_number,'WO-20');assert.equal(a.showReportsPanel,true);});
test('failed report clears stale totals and prevents exporting them',async()=>{const a=app();a.consumptionReport=result;a.apiCall=async()=>{throw Error('offline');};await a.loadConsumptionReport();assert.equal(a.consumptionReport,null);assert.match(a.reportError,/offline/);});
test('invalid date range makes no request',async()=>{const a=app();a.reportForm.start_date='2026-10-06';a.reportForm.end_date='2026-10-05';let sent=false;a.apiCall=async()=>{sent=true;};await a.loadConsumptionReport();assert.equal(sent,false);assert.match(a.reportError,/date/i);});
test('pagination preserves filters and full totals',async()=>{const a=app();a.consumptionReport=result;a.reportForm.allDates=true;a.apiCall=async(p)=>{assert.match(p,/offset=100/);return {...result,offset:100};};await a.loadConsumptionReport(100);assert.equal(a.reportOffset,100);assert.equal(a.consumptionReport.totals.events,205);});
test('editing filters marks displayed report stale until refreshed',()=>{const a=app();a.consumptionReport=result;a.reportDirty=false;a.markReportDirty();assert.equal(a.reportDirty,true);});
test('late response after changing users does not reveal previous user history',async()=>{const a=app();a.reportForm.allDates=true;let resolve;a.apiCall=()=>new Promise(r=>resolve=r);const pending=a.loadConsumptionReport();a.currentUser={id:4,role:'engineer'};resolve(result);await pending;assert.equal(a.consumptionReport,null);});
test('CSV downloads all applied filters without page limits',async()=>{let requested,clicked=false;const c={console,setTimeout:()=>{},URLSearchParams,Date,Intl,fetch:async(url,options)=>{requested=url;assert.equal(options.credentials,'include');return {ok:true,blob:async()=>({})};},URL:{createObjectURL:()=> 'blob:test',revokeObjectURL:()=>{}},document:{body:{appendChild:()=>{}},createElement:()=>({click:()=>{clicked=true;},remove:()=>{}})}};vm.createContext(c);vm.runInContext(fs.readFileSync('static/script.js','utf8'),c);const a=c.inventoryApp();a.currentUser={id:3,role:'engineer'};a.consumptionReport=result;a.reportDirty=false;a.reportAppliedQuery='work_order_number=WO-20';await a.exportConsumptionReport();assert.match(requested,/consumption.csv\?work_order_number=WO-20$/);assert.equal(clicked,true);a.reportDirty=true;clicked=false;await a.exportConsumptionReport();assert.equal(clicked,false);});
