const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
function app(){const c={console,setTimeout:()=>{}};vm.createContext(c);vm.runInContext(fs.readFileSync('static/script.js','utf8'),c);const a=c.inventoryApp();a.currentUser={id:3,role:'engineer'};return a;}
const row={store_id:10,part_id:20,store_name:'Need',part_number:'P',quantity:1,min_threshold:5,incoming_quantity:1,internal_quantity:2,purchase_quantity:1,suggestions:[{inventory_id:30,store_name:'Central',quantity:2,can_dispatch:true}]};
test('plan filtering never recomputes or double assigns server allocations',()=>{const a=app();a.replenishmentPlan={rows:[row,{...row,store_id:11}]};a.replenishmentStoreFilter='10';assert.equal(a.replenishmentRows.length,1);assert.equal(a.replenishmentRows[0].internal_quantity,2);});
test('minimum selection excludes allocated rows and saves expected minimum',async()=>{const a=app();a.inventory=[{store_id:10,part_id:20,is_allocated:true,min_threshold:99},{store_id:10,part_id:20,is_allocated:false,min_threshold:5}];a.minimumForm.store_id='10';a.minimumForm.part_id='20';a.selectMinimum();assert.equal(a.minimumForm.min_threshold,5);let body;a.apiCall=async(path,opt)=>{if(path==='/inventory/minimum')body=JSON.parse(opt.body);return {rows:[]};};a.loadInventory=async()=>{};await a.saveMinimum();assert.deepEqual(body,{store_id:10,part_id:20,min_threshold:5,expected_minimum:5});});
test('failed plan refresh clears actionable stale suggestions and export',async()=>{const a=app();a.replenishmentPlan={rows:[row]};a.apiCall=async()=>{throw Error('offline');};assert.equal(await a.loadReplenishment(),false);assert.equal(a.replenishmentPlan,null);assert.match(a.replenishmentError,/offline/);let exported=false;a.downloadCSV=()=>{exported=true;};await a.exportProcurementCSV();assert.equal(exported,false);});
test('review refreshes plan and opens existing dispatch form without writing',async()=>{const a=app();let writes=0;a.apiCall=async(_p,o)=>{if(o)writes++;return {rows:[row]};};a.loadInventory=async()=>{a.inventory=[{id:30,quantity:10}];};await a.reviewReplenishmentTransfer(row,row.suggestions[0]);assert.equal(writes,0);assert.equal(a.showTransferModal,true);assert.equal(a.transferForm.to_store_id,10);assert.equal(a.transferForm.quantity,2);assert.equal(a.transferForm.replenishment,true);await a.transferItem({id:40});assert.equal(a.transferForm.replenishment,false);});
test('changed suggestions require another review instead of opening stale transfer',async()=>{const a=app();a.apiCall=async(p)=>p==='/inventory'?[{id:30,quantity:10}]:({rows:[{...row,suggestions:[{...row.suggestions[0],quantity:1}]}]});await a.reviewReplenishmentTransfer(row,row.suggestions[0]);assert.equal(a.showTransferModal,false);assert.match(a.replenishmentError,/changed/i);});
test('procurement export refreshes and includes only remaining purchases',async()=>{const a=app();a.apiCall=async()=>({rows:[row,{...row,store_id:11,purchase_quantity:0}]});let data;a.downloadCSV=(headers,rows)=>{data={headers,rows};};await a.exportProcurementCSV();assert.equal(data.rows.length,1);assert.equal(data.rows[0].at(-1),1);assert.match(data.headers.join(' '),/suggested/i);});
test('real inventory refresh followed by failed plan refresh never opens dispatch',async()=>{const a=app();a.showLowStockPanel=true;const calls=[];a.apiCall=async(p)=>{calls.push(p);if(p==='/inventory')return [{id:30,quantity:10}];throw Error('offline');};await a.reviewReplenishmentTransfer(row,row.suggestions[0]);assert.equal(a.showTransferModal,false);assert.deepEqual(calls,['/inventory','/inventory/replenishment']);assert.equal(a.replenishmentPlan,null);});
test('review using real inventory refresh fetches the plan once without writes',async()=>{const a=app();a.showLowStockPanel=true;const calls=[];a.apiCall=async(p,o)=>{assert.equal(o,undefined);calls.push(p);return p==='/inventory'?[{id:30,quantity:10}]:{rows:[row]};};await a.reviewReplenishmentTransfer(row,row.suggestions[0]);assert.equal(a.showTransferModal,true);assert.deepEqual(calls,['/inventory','/inventory/replenishment']);});
test('low stock labels exclude disabled, fulfilled and allocated targets',()=>{const a=app();assert.equal(a.isLowStock({quantity:0,min_threshold:0,is_allocated:false}),false);assert.equal(a.isLowStock({quantity:5,min_threshold:5,is_allocated:false}),false);assert.equal(a.isLowStock({quantity:1,min_threshold:5,is_allocated:true}),false);assert.equal(a.isLowStock({quantity:1,min_threshold:5,is_allocated:false}),true);});
test('saving a minimum refreshes the dashboard low stock count',async()=>{const a=app();a.minimumForm={store_id:10,part_id:20,min_threshold:5,expected_minimum:0};a.apiCall=async()=>({});a.loadInventory=async()=>{};a.loadReplenishment=async()=>true;let refreshes=0;a.loadStats=async()=>{refreshes++;};await a.saveMinimum();assert.equal(refreshes,1);});
